# Generated by Django 5.0.4 on 2024-04-25 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customersmodel_email'),
        ('buyer', '0002_contactusmodel_delete_registration'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customersmodel')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.productsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
