# Generated by Django 5.0.4 on 2024-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='is_added_address',
            field=models.BooleanField(default=False),
        ),
    ]
