# Generated by Django 5.0.4 on 2024-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customersmodel_is_added_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
